### ISSUE TITLE
main.cc - used variable p

### ISSUE THREAD

**Issue by alexnardini** [petershirley/raytracinginoneweekend#14] opened 2018-09-15 05:41 UTC
At line number 100 of "main.cc" :
`vec3 p = r.point_at_parameter(2.0);`
I think this is not needed at all, is it?

**Comment by vchizhov** [comment] 2018-09-15 22:52
It is not, it's just something leftover from a prev version most likely.

**Comment by alexnardini** [comment] 2018-09-15 23:13
Thank you for confirming.

**Comment by hollasch** [comment] 2019-06-29 08:23
Duplicate of #1

**Closed by hollasch** 2019-06-29 08:23 UTC
